### ISSUE TITLE
Incorrect texture color

### ISSUE THREAD

**Issue by Kyouha2020** [China-smallpc/SPC-Util#10]
![image](https://user-images.githubusercontent.com/59816797/92319483-56575980-f04b-11ea-9ac0-07e6b723fa4c.png)
Color is incorrect, why?

**Comment by China-smallpc** [comment]
you should select correct texture mapper file ( texture/ios.json )

**Comment by Kyouha2020** [comment]
> you should select correct texture mapper file ( texture/ios.json )

But literally I'm using it.

**Comment by China-smallpc** [comment]
what's your version?

**Comment by Kyouha2020** [comment]
> what's your version?

Latest version of SPC Util and PvZ2 8.4.1
