### ISSUE TITLE
AnimUtil:PopAnimUtil:Encoder:DeCode

### ISSUE THREAD

**Issue by lengthyname** [China-smallpc/SPC-Util#2]
I'm getting this error when i use the program to decode a PAM file to JSON. I installed the program properly, like instructed in the Readme.

**Comment by China-smallpc** [comment]
this function is private, only mr can use. I will release new version and this version can convert between pam & xfl(flash) file, some days later.

**Comment by lengthyname** [comment]
Ok. I'll be waiting.
